[toc]
### 异常的概念
1. Java异常是java提供的用于处理程序中错误的一种机制。
2. 所谓错误是指在程序运行的过程中发生的一些异常事件。
3. 设计良好的程序应该在异常发生时提供处理这些错误的方法，使得程序不会因为异常的发生而阻断或产生不可预计的结果。
4. java程序的执行过程中如发生异常事件，可以生成一个异常类对象，该异常对像封装了异常事件的信息并将被提交给java运行时系统，这个过程可以称为抛出（throw）异常。
5. 当java运行时系统接收到异常对象时，会寻找能处理这一异常的代码并把当前异常对象交给其处理，这一过程称为捕获（catch）异常。

### 异常的分类
1. Errot：称为错误，由Java虚拟机生成并抛出，包括都太链接失败、虚拟机错误等，程序对其不做处理。
2. Exception：所有异常类的父类，其子类对应了各种各样可能出现的异常事件，一般需要用户显式的声明或捕获。
3. Runtime Exception：一类特殊的异常，如被0除、数组下标超范围等，其产生比较频繁，处理麻烦，如果显式的声明或捕获将会对程序可读性和运行效率影响很大。因此有系统自动检测并假它们交给缺省的异常处理程序（用户可不必对其处理）。

![分类图]()

### 异常的捕获和处理
1. `try`：对被`try`包括的语句进行异常捕获（**有异常的时候**）。
2. `catch`：当`try`包括的语句出现异常时，立即离开当前语句，与所有的`catch`语句进行类名对比。如果捕获的异常与`catch`的类名相同或者与**它的子类**相同，则会进入该`catch`语句块（成为捕获的异常）。如果与任何一个`catch`语句块都不相同，则抛出这个异常。
3. `finally`：当任何`try`和`catch`语句结束的时候都会执行`finally`语句。
```java
//异常处理
//声明方法的异常
public class AppTest {
    public static void main(String[] args) throws IOException {
        AppTest a = new AppTest();
        a.f2();
        a.f();
    }
    void f() throws FileNotFoundException, IOException {
        //这里抛出了FileNotFoundException异常
        FileInputStream f = new FileInputStream("1.txt");
        int b;
        //这里read抛出了一个IOException异常
        b = f.read();
        while (b != -1){
            System.out.println((char) b);
            b = f.read();
        }
    }

    //调用方法 获取异常
    //FileNotFoundException继承IOException
    //抛出异常的先后顺序：先写子类在写父类
    void f2(){
        try {
            this.f();
        } catch (FileNotFoundException Fe) {
            Fe.printStackTrace();
        } catch (IOException e){
            System.out.println(e.getMessage());
        }
    }
}
```

### final、finally和finalize区别
- `final`是一个关键字，修饰最终的、不变的
- `finally`也是一个关键字，和`try`联合使用，使用在异常处理机制中，改代码块中的代码一定会执行。
- `finalize`是一个标识符，是`Object`类中的一个方法名，这个方法由垃圾回收站GC负责调用。

### Java中自定义异常
- 编写一个类继承Exception（编译时异常）或者RuntimeException（运行时异常）。
- 提供两个构造方法，一个无参数，一个带有String参数。

> throws：在方法声明位置上使用，表示上报异常信息给调用者。
> throw：手动抛出异常